ForestAdmin/forest-express

CHANGELOG.md
package.json

Fixes: https://github.com/ForestAdmin/forest-express-mongoose/issues/27

Dependencies - Freeze the dependencies versions to reduce packages versions changes between projects/environments

---

CHANGELOG.md
index.js

Fixes https://github.com/ForestAdmin/forest-express/issues/6 and https://github.com/ForestAdmin/forest-express-mongoose/issues/33

Configurations - Users can specify the directory for Forest Smart Implementation

---

CHANGELOG.md
index.js
services/auth.js

Fixes: https://github.com/ForestAdmin/forest-express-mongoose/issues/36

Configuration - Fix bad authentication when a custom path is configured

---

CHANGELOG.md
serializers/resource.js

This PR comes with this one: https://github.com/ForestAdmin/forest-express-sequelize/pull/83

[+] Types Support - Support Dateonly field type

---

CHANGELOG.md
package.json
routes/sessions.js

This pull request is the same as https://github.com/ForestAdmin/forest-express/pull/68 with some light improvements.

[-] Performances - Make the password comparison asynchronous on session creation

---

CHANGELOG.md
index.js

[+] Technical - Send ORM version and database type in apimap.

---

CHANGELOG.md
serializers/resource.js

[*] Collections - Correctly serialize collections that begin with an underscore.

---

CHANGELOG.md
serializers/resource.js

[*] Serializer - Throw an error if the association doesn't exist in serializer.

---

CHANGELOG.md
package.json

[-] Warnings - Remove a potential console deprecation warning

---

CHANGELOG.md
index.js

[+] Search - Developers can configure in which fields the search will be executed

---

CHANGELOG.md
integrations/layer/index.js
integrations/layer/routes.js
integrations/layer/serializers/conversation.js
integrations/layer/serializers/conversations.js
integrations/layer/serializers/messages.js
integrations/layer/setup.js

[+] Integrations - Add a first version of Layer integration

---

CHANGELOG.md
index.js
package.json

[*] Exports - Fix bad initial implementation for exports authentication

---

CHANGELOG.md
integrations/layer/index.js
integrations/layer/routes.js
integrations/layer/serializers/conversations.js
integrations/layer/serializers/messages.js
integrations/layer/services/conversation-getter.js
integrations/layer/services/conversations-getter.js
integrations/layer/services/messages-getter.js
integrations/layer/setup.js

[-] Integrations - Add the Layer integration

---

CHANGELOG.md
utils/code-syntax-inspector.js

[*] Code Inspection - Fix Forest customisation code inspection to be recursive through directories

---

CHANGELOG.md
package.json
services/csv-exporter.js

[*] Exports - Escape special characters for the string fields.

---

CHANGELOG.md
generators/schemas.js
index.js
integrations/close.io/index.js
integrations/index.js
integrations/intercom/index.js
integrations/layer/index.js
integrations/mixpanel/index.js
integrations/stripe/index.js
serializers/resource.js

[*] Integrations - Display models "mapping" errors if any

---

CHANGELOG.md
index.js

Allow users to call a ResourcesRoute from their app.

---

CHANGELOG.md
integrations/layer/routes.js
integrations/layer/services/conversations-getter.js
integrations/layer/setup.js
integrations/mixpanel/setup.js

[*] Integrations - Catch an error if the user is not found by the Layer API

---

CHANGELOG.md
services/csv-exporter.js

[*] Export - Fix datetime formatting regression introduced by liana version 1.2.3

---

CHANGELOG.md
index.js

[-] Initialization - Display an explicit error log if a model cannot be loaded properly

---

CHANGELOG.md
index.js

Ignore non-files in model loading (issue #106)

---

CHANGELOG.md
index.js

[+] Smart Collections - Add a field parameter to allow the sorting on it.

---

CHANGELOG.md
package.json

Fix https://github.com/ForestAdmin/forest-express/issues/110
Fix https://github.com/ForestAdmin/forest-express-mongoose/issues/70

[*] Initialisation - Prevent bad ES2017 syntax error detections on initialisation

---

CHANGELOG.md
index.js
integrations/stripe/setup.js

[*] Stripe - Fix the 'mapping' collection name on Express/Mongoose

---

CHANGELOG.md
services/allowed-users-finder.js

[-] Sessions - Display a clean error message if the renderingId and envSecret are missing or inconsistent

---

CHANGELOG.md
services/smart-fields-values-injector.js

[*] Smart Fields - Prevent crash when trying to compute Smart Field value.

---

CHANGELOG.md
deserializers/resource.js
serializers/resource.js

[+] Types Support - Support Point field type

---

CHANGELOG.md
routes/associations.js
routes/resources.js
serializers/resource.js

[-] Smart Fields - Do the Smart Fields values injection in the Serializer to simplify Smart Relationships implementation

---

CHANGELOG.md
index.js

[+] Custom Domain - Add CORS_ORIGINS support

---

CHANGELOG.md
serializers/resource.js

[*] Summary View - Fix potential Summary View freeze on records having "Point" type fields

---

CHANGELOG.md
serializers/resource.js
services/smart-fields-values-injector.js

[*] Smart Fields - Prevent Smart Fields values injection errors on related data retrieval

---

CHANGELOG.md
deserializers/resource.js

[+] Smart BelongsTo - Developers can now implement Smart BelongsTo values updates

---

CHANGELOG.md
generators/schemas.js
index.js
integrations/close.io/setup.js
integrations/intercom/setup.js
integrations/layer/setup.js
integrations/mixpanel/setup.js
integrations/stripe/setup.js

[+] Smart Fields - Add a isFilterable option to let them appear the filters selection.

---

CHANGELOG.md
package.json
yarn.lock

[*] Security - Remove a vulnerability by upgrading Moment.js library

---

CHANGELOG.md
index.js
services/auth.js

[*] Authentication - Developers whom want to extend the Admin API can now use the authentication for the overridden routes

---

CHANGELOG.md
routes/stats.js
services/error.js

[+] Charts - Users can create charts using raw database queries with the Live Query option

---

CHANGELOG.md
deserializers/resource.js

Fix: https://github.com/ForestAdmin/forest-express/issues/141

[*] Smart Fields - Fix concurrency between Smart Fields setters and enable multiple setters to work properly on a record update

---

CHANGELOG.md
test/routes/sessions-google.js

[*] Tests - Fix Google session creation test

---

CHANGELOG.md
services/apimap-sender.js
services/apimap-sorter.js
test/services/apimap-sorter.js

[-] Apimap - Prevent random sorting collections and useless updates.

---

CHANGELOG.md
index.js
services/apimap-sorter.js

[*] Smart Actions - Display the Smart Actions form fields in the declaration order

---

CHANGELOG.md
index.js

[*] Smart Actions - Users can define Smart Actions only available in a record detail

---

CHANGELOG.md
index.js

[+] Smart Actions - Developers can define Smart Actions that can send their request to a different endpoint than the current environment endpoint

---

CHANGELOG.md
routes/associations.js
routes/resources.js

[+] MongoDB HasMany - Allow documents embedded to an array to be editable

---

routes/associations.js

[+] Delete records directly from a hasMany listing

---

CHANGELOG.md
generators/schemas.js

[-] Collections - Allow collection customization before liana initialization

---

CHANGELOG.md
index.js
integrations/close.io/routes.js
package.json
routes/actions.js
yarn.lock

[+] Smart Actions - "Single" type Smart Action forms can now be prefilled with contextual values

---

.eslintrc.js
CHANGELOG.md
index.js
middlewares/ip-whitelist.js
package.json
services/ip-whitelist.js
test/helpers/request.js
test/routes/sessions-google.js
utils/error-messages.js
yarn.lock

[+] Security - Protect the liana by adding an IP Whitelist

---

CHANGELOG.md
index.js
middlewares/ip-whitelist.js
routes/ip-whitelist-rules.js

[+] IP Whitelist - Refresh IP Whitelist on liana when update on front

---

CHANGELOG.md
index.js
routes/sessions.js

[+] IP Whitelist - Unlock a user/editor by sending and email

---

.eslintrc.js
CHANGELOG.md
index.js
middlewares/ip-whitelist.js
package.json
routes/ip-whitelist-rules.js
routes/sessions.js
services/auth.js
services/ip-whitelist.js
test/helpers/request.js
test/routes/sessions-google.js
utils/error-messages.js
yarn.lock

[+] Premium Security - Add IP Whitelist feature

---

CHANGELOG.md
src/routes/associations.js
src/routes/resources.js

[+] Search - Display highlighted matches on table view when searching

---

CHANGELOG.md
src/routes/associations.js
src/routes/resources.js
src/serializers/resource.js
src/services/smart-fields-values-injector.js

[-] Search - Display highlighted match on smart fields.

---

CHANGELOG.md
package.json
src/index.js
src/middlewares/ip-whitelist.js
src/middlewares/permissions.js
src/routes/resources.js
src/services/forest-server-requester.js
src/services/ip-whitelist.js
src/services/permissions-checker.js
src/utils/error-messages.js
test/helpers/request.js
test/services/permissions.js
yarn.lock

[+] Permissions - Add a permission mechanism to protect the data accordingly to the UI configuration

---

CHANGELOG.md
src/middlewares/permissions.js
src/routes/resources.js

[+] Permissions - Allow search on belongs_to when relation collection is hidden

---

CHANGELOG.md
src/routes/stats.js

[+] Charts - Users can create "Leaderboard" charts

---

src/routes/stats.js

Review rename

---

CHANGELOG.md
src/index.js

Technical - Add a new apimap property "relationship"

---

CHANGELOG.md
src/deserializers/ip-whitelist.js
src/services/ip-whitelist.js

[*] IP Whitelist - Fix broken ip range of form 'x.x.x.x - x.x.x.x'

---

CHANGELOG.md
src/index.js
src/routes/stats.js
src/serializers/stat.js

[+] Charts - Users can create Objective and Leaderboard Charts

---

CHANGELOG.md
src/serializers/resource.js

[*] DateOnly Fields - Fix potential bad values for projects using Sequelize 4+.

---

CHANGELOG.md
src/middlewares/permissions.js
src/services/forest-server-requester.js
src/services/permissions-checker.js
test/services/permissions.js

[*] Permissions - Fix automated permission for projects having multiple teams

---

CHANGELOG.md
src/integrations/intercom/routes.js
src/integrations/intercom/services/conversations-getter.js
src/integrations/intercom/setup.js

[*] Intercom Integration - Users can now access to the Intercom Details page

---

CHANGELOG.md
src/integrations/mixpanel/index.js
src/integrations/mixpanel/routes.js
src/integrations/mixpanel/serializers/mixpanel-events.js
src/integrations/mixpanel/services/mixpanel-events-getter.js
src/integrations/mixpanel/setup.js

To test, follow the instructions here: https://trello.com/c/DeSWsMad/2641-8-integrations-mixpanel-last-events-on-all-stacks

[+] Integrations - Mixpanel last events 

---

CHANGELOG.md
src/routes/associations.js
src/routes/resources.js
src/serializers/resource.js

[-] Performance - Improve the speed of listing the records by executing their count into another request

---

CHANGELOG.md
package.json
src/routes/sessions.js
src/services/authorization-finder.js
src/services/google-authorization-finder.js
src/services/login-handler.js
src/services/server-response-handler.js
src/services/two-factor-registration-confirmer.js
test/routes/sessions.js
yarn.lock

[+] Authentication - Add two factor authentication login

---

src/routes/sessions.js
src/services/authorization-finder.js
src/services/google-authorization-finder.js
src/services/login-handler.js
src/services/two-factor-registration-confirmer.js
test/routes/sessions.js

Authentication - 2FA review fixes

---

CHANGELOG.md
src/services/login-handler.js

[-] Authentication - Improve the log message when 2FA secret key is not set

---

CHANGELOG.md
src/utils/integrations.js

[*] Smart Actions - Fix a possible crash with Stripe integration

---

CHANGELOG.md
src/middlewares/permissions.js
src/services/permissions-checker.js

[+] Smart Actions - Check if a user is allowed to execute a smart action

---

CHANGELOG.md
src/index.js

[+] Technical - On start, create a forestadmin.json file that contains the apimap definition

---

CHANGELOG.md
src/index.js
src/serializers/schema.js
src/services/apimap-sender.js
src/services/schema-file-updater.js

We want to have the same apimap as the toolbelt

---

CHANGELOG.md
src/index.js

[-] Security - Do not pass session token in query params while downloading collections records

---

CHANGELOG.md
src/services/base-filters-parser.js

Needed for mongoose generic filters

[*] Filters - Empty associations array on flat condition without belongsTo

---

CHANGELOG.md
src/serializers/resource.js

[-] Technical - Apply ESLint rules to an existing code file

---

.npmignore
CHANGELOG.md

[*] NPM Publish - Do not send local environment variables on package publish

---

CHANGELOG.md
src/index.js

[*] Routes - Ensure that admin middlewares are configured for admin API routes only and does not interfere with other project routes

---

CHANGELOG.md
src/services/base-filters-parser.js

 [-] Technical - Change functions of filter parser to async

---

.babelrc
.eslintrc.js
CHANGELOG.md
package.json
src/index.js
src/middlewares/permissions.js
src/routes/associations.js
src/routes/resources.js
src/serializers/resource.js
src/services/config-store.js
src/services/exposed/abstract-records-service.js
src/services/exposed/record-creator.js
src/services/exposed/record-getter.js
src/services/exposed/record-remover.js
src/services/exposed/record-updater.js
src/services/exposed/records-counter.js
src/services/exposed/records-exporter.js
src/services/exposed/records-getter.js
src/services/state-manager.js
yarn.lock

[+] Routes - Expose the record services and the permissions middleware

---

CHANGELOG.md
src/index.js

[+] Technical - `.forestadmin-schema` now keeps track of engine and framework names and versions

---

.eslintrc.js
CHANGELOG.md
src/index.js
src/utils/project-directory.js
test/utils/project-directory.test.js

To test this out : 
- On devel, try to start your project from the parent directory, you will see that the forest admin schema is written in the parent directory instead of the project directory. 
Using this branch :
- Starting your project on its folder writes the forestadmin-schema file in it. 
- Starting your project on parent's directory writes the forestadmin-schema file in it. 
- Using a yarn sym link to link this package to your project works too.

[*] ForestAdmin-Schema - The schema file is now written in the project directory, wherever the startup command has been hinted from.

---

CHANGELOG.md
src/services/smart-fields-values-injector.js

[*] Smart Relationships - Prevent server crash in case of "cyclic" Smart BelongsTo declaration

---

CHANGELOG.md
src/index.js
src/services/exposed/abstract-records-service.js
src/services/exposed/record-serializer.js

[+] Smart Relationship - Expose a serializer to simplify the serialization

---

CHANGELOG.md
src/index.js
src/integrations/intercom/services/attributes-getter.js
src/integrations/intercom/services/conversation-getter.js
src/integrations/intercom/services/conversations-getter.js
src/integrations/stripe/services/invoices-getter.js
src/integrations/stripe/services/payments-getter.js
src/integrations/stripe/services/sources-getter.js
src/integrations/stripe/services/subscriptions-getter.js
src/routes/actions.js
src/services/apimap-sorter.js
src/services/auth.js
src/services/authorization-finder.js
src/services/error-handler.js
src/services/logger.js
src/services/smart-fields-values-injector.js
src/services/two-factor-registration-confirmer.js

The request has a bit changed. I tried to fix the actual behavior of `logger`:
- Add space where needed (no more `Unexpected error:Using this message`)
- Display stack trace if present.
- Change code where error message was displayed twice (remove `error.message` in first string).
Now, this code:
```javascript
logger.error('Error');
try {
throw new Error('Invalid column name `id`.');
} catch (e) {
logger.error('Unexpected error: ', e);
}
logger.error('Unexpected error: my message');
try {
throw new Error('Invalid column name `id`.');
} catch (e) {
logger.error(`Unexpected error: ${e.message}`, e);
}
logger.info('hello', {});
try {
throw new Error('Invalid column name `id`.');
} catch (e) {
logger.warn('Foobar. ', e);
}
```
Displays:
```
[forest] 🌳🌳🌳  Error
[forest] 🌳🌳🌳  Unexpected error: …
```

[*] Logger - Improve formatting, add stack if present, do not display error messages twice

---

CHANGELOG.md
src/index.js

[*] Smart actions - Ignore smart actions that do not have a name (display a warning

---

CHANGELOG.md
test/deserializers/params-fields.test.js

Tests - Add params fields deserializer test

---

CHANGELOG.md
src/deserializers/ip-whitelist.js
test/deserializers/ip-whitelist.test.js

[+] Tests - Add tests for IP whitelist deserializer

---

CHANGELOG.md
src/index.js

[-] Smart Collections - Do not insert Smart Collections unless they contain at least one declared field

---

CHANGELOG.md
src/routes/sessions.js
src/services/authorization-finder.js
src/services/login-handler.js

See detailed description in the [Trello card](https://trello.com/c/xxi9pOEO/4016-logging-in-a-project-wrong-error-messages-are-shown-when-a-server-runs-on-the-correct-app-url-with-the-wrong-forestenvsecret).

[*] Login - Make the login error messages brought up to the end client through toasts more accurate

---

.travis.yml
commitlint.config.js
package.json
scripts/release.js
yarn.lock

- ~~[ ] So it could be removed~~ it has not been removed because update coverage needs it.
- ~~[ ] Send notification on Slack (needs an App) => maybe use the current system POSPONED~~
See: https://travis-ci.org/ForestAdmin/forest-express/jobs/618651403?utm_medium=notification&utm_source=github_status

feat: add semantic release

---

package.json

See: https://github.com/ForestAdmin/forest-express/pull/339#pullrequestreview-344704528

chore(technical): `package.json` script section in alphabetical order

---

.github/PULL_REQUEST_TEMPLATE.md

chore(technical): update PR template to conventional commits specification

---

package.json
yarn.lock

Previous version has been detected as a security issue.

fix(security): update npm to 6.13.4 version

---

commitlint.config.js

Allow this PR title to be edited: https://github.com/ForestAdmin/forest-express/pull/338#pullrequestreview-345266026

chore(commitlint): allow up to 100 characters in commit header messages

---

.github/PULL_REQUEST_TEMPLATE.md
.travis.yml
CHANGELOG.md
commitlint.config.js
package.json
scripts/release.js
yarn.lock

@rap2hpoutre Don't forget to **_rebase and merge_** (not **_squash and merge_**)

chore: release

---

.babelrc
.eslintrc.js
package.json
yarn.lock

update babel to latest version

chore(babel): add support for optional chaining

---

src/deserializers/query.js
src/routes/associations.js
src/services/exposed/records-getter.js
src/services/ids-from-request-retriever.js

fix: select all from related tables

---

commitlint.config.js

chore: commit lint length

---

.travis.yml

ci: remove dry run

---

.releaserc.js
package.json
yarn.lock

ci: update changelog and commit changes

---

CHANGELOG.md
src/index.js
test/helpers/create-server.js
test/routes/healthcheck.test.js
test/routes/liana.init.error.test.js
test/routes/liana.init.test.js
test/routes/sessions-google.test.js
test/routes/sessions.test.js

feat: make Liana.init return a promise resolving when all is up

---

package.json
yarn.lock

ci: update semantic release

---

CHANGELOG.md

chore(changelog): fix changelog

---

.travis.yml

fix(ci): yarn build before release

---

README.md
test/deserializers/resource.test.js
test/fixtures/users-schema.js
test/services/ip-whitelist.test.js
test/utils/data.test.js
test/utils/integrations.test.js
test/utils/schema.test.js

test: increase code coverage

---

src/integrations/intercom/serializers/intercom-conversation.js
src/integrations/intercom/serializers/intercom-conversations.js

fix(integration): fix intercom conversations display with API v2

---

src/index.js

fix(wording): fix a typo in the missing .forestadmin-schema.json file error message

---

src/integrations/intercom/setup.js

fix(integration): fix intercom details display

---

src/integrations/intercom/index.js
src/integrations/intercom/routes.js
src/integrations/intercom/services/attributes-getter.js
src/integrations/intercom/services/contact-getter.js
src/integrations/intercom/services/conversations-getter.js
src/integrations/intercom/setup.js

feat(integration): allow user to choose custom mapping values for intercom integration

---

src/middlewares/permissions.js
src/services/permissions-checker.js
test/services/permissions.test.js

I already tested this out, and it is quite hard to setup for testing. If you want, I can help you setting up everything needed to test this out 👍 
[ClickUp](https://app.clickup.com/t/4jq80f)

feat(smart-action): allow users to protect their smart-action APIs from unauthorized usage

---

package.json
yarn.lock

fix(security): patch dependencies vulnerabilities (minimist, acorn)

---

README.md

docs(readme): remove release section

---

README.md

chore(readme): add the semantic release tag in the readme

---

.releaserc.js

Question:
https://semantic-release.gitbook.io/semantic-release/support/faq#why-is-the-package-jsons-version-not-updated-in-my-repository
Response:
https://github.com/semantic-release/git#examples
Other:
https://github.com/semantic-release/git/issues/88

ci: update the package version during a release

---

.travis.yml

ci: simplify the publish job definition

---

.releaserc.js
package.json
yarn.lock

Uses this package:
https://github.com/juliuscc/semantic-release-slack-bot
With this Slack app:
https://api.slack.com/apps/A0132LC7EHZ/general?
With a single variable set in Travis:

ci: publish releases notes on Slack

---

README.md

docs(readme): update community badge

---

src/middlewares/permissions.js
src/services/permissions-checker.js
test/services/permissions.test.js

feat(scope): validate scope context on list request

---

src/index.js
src/services/exposed/records-remover.js

See: https://share.clickup.com/t/h/62m7ah/1ZWH1NWIZQPH2KL

fix(services): create and expose records remover

---

src/index.js

fix(2FA): no warning message related to 2FA salt is displayed if none has been set

---

src/services/permissions-checker.js

fix: ensure scope's value is a string

---

src/generators/schemas.js
src/integrations/close.io/routes.js
src/integrations/close.io/serializers/closeio-lead-emails.js
src/integrations/close.io/serializers/closeio-leads.js
src/integrations/intercom/routes.js
src/integrations/intercom/serializers/intercom-attributes.js
src/integrations/intercom/serializers/intercom-conversation.js
src/integrations/intercom/serializers/intercom-conversations.js
src/integrations/layer/routes.js
src/integrations/layer/serializers/conversations.js
src/integrations/layer/serializers/messages.js
src/integrations/mixpanel/routes.js
src/integrations/mixpanel/serializers/mixpanel-events.js
src/integrations/stripe/routes.js
src/integrations/stripe/serializers/bank-accounts.js
src/integrations/stripe/serializers/cards.js
src/integrations/stripe/serializers/invoices.js
src/integrations/stripe/serializers/payments.js
src/integrations/stripe/serializers/subscriptions.js

Removes the new keyword from the call to schema adapter
Linked to Linked to CU-7rv8fc

improvement: change incorrect call to external schema adapter

---

src/serializers/schema.js
src/services/schema-file-updater.js
test/services/schema-file-updater.test.js

feat: serialize the new property isPrimaryKey

---

package.json
yarn.lock

I added the dev dependency `@types/jest`, allowing developpers to have auto-completion when writing tests.

chore: improve developper experience by allowing auto completion in tests

---

src/index.js

fix(authentication): allow 'null' origin for oidc callback

---

src/services/request-analyser.js
test/services/request-analyzer.test.js

fix(authentication): correctly extract the requested url from headers

---

src/context/init.js
src/services/authentication.js
src/services/oidc-client-manager.js
src/services/oidc-configuration-retriever.js
test/routes/authentication.test.js
test/services/authentication.test.js
test/services/oidc-client-manager.test.js

feat(authentication): register a new oidc client on first authentication

---

src/index.js

refactor: init now uses async await instead of promises

---

src/context/init.js
src/serializers/schema.js
src/services/apimap-sorter.js
test/services/apimap-sorter.test.js

(I just moved some code/use context injection/fix tests here - CC issues were not introduced here)

refactor: inject ApimapSorter service and get dependencies from injection

---

src/context/init.js
src/index.js
src/services/apimap-fields-formater.js
test/services/apimap-fields-formater.test.js

refactor: inject ApimapFieldFormater service and get dependencies from injection

---

src/context/init.js
src/index.js
src/middlewares/permissions.js
src/routes/resources.js
src/services/config-store.js
src/services/exposed/abstract-records-service.js
test/services/config-store.test.js

refactor(init): inject config-store and validation init configuration

---

src/index.js
src/services/config-store.js
test/index.test.js
test/services/config-store.test.js

chore: remove usage of modelsDir option

---

src/context/init.js
src/index.js
src/integrations/close.io/index.js
src/integrations/close.io/routes.js
src/integrations/intercom/index.js
src/integrations/intercom/services/contact-getter.js
src/integrations/intercom/services/integration-informations-getter.js
src/integrations/intercom/setup.js
src/integrations/layer/index.js
src/integrations/layer/routes.js
src/integrations/layer/setup.js
src/integrations/mixpanel/index.js
src/integrations/mixpanel/routes.js
src/integrations/mixpanel/setup.js
src/integrations/stripe/index.js
src/integrations/stripe/routes.js
src/integrations/stripe/setup.js
src/routes/associations.js
src/routes/stats.js
src/services/exposed/abstract-records-service.js
src/services/exposed/records-getter.js
src/services/integration-informations-getter.js
src/services/models-manager.js
test/helpers/create-server.js
test/index.test.js
test/services/models-manager.test.js

chore: create models manager

---

src/context/init.js
src/index.js
src/services/schema-file-updater.js
test/services/schema-file-updater.test.js

refactor: move SchemaFileUpdater to class with DI

---

src/services/config-store.js
src/services/exposed/record-serializer.js
src/services/models-manager.js
test/helpers/create-server.js
test/index.test.js
test/services/config-store.test.js
test/services/models-manager.test.js

chore: refactor getModels function and handle exclude and include models option

---

src/index.js
src/routes/actions.js
test/routes/actions.test.js

Related PRs:
- https://github.com/ForestAdmin/forest-express/pull/537
- https://github.com/ForestAdmin/forest-express/pull/539

refactor: migrate Actions routes to class and use DI

---

src/context/init.js
src/services/schema-file-updater.js
test/services/schema-file-updater.test.js

chore: inject fs instead of writeFileSync function

---

.travis.yml

ci: enable beta release via semantic-release

---

.travis.yml

ci: enable beta to deploy

---

src/routes/actions.js
test/routes/actions.test.js

fix(technical): remove useless data property from load hook controller

---

src/index.js

To test it efficiently, you will need the updated [server](https://github.com/ForestAdmin/forestadmin-server/pull/1820)

fix(schema): do not generate `framework`, `framework_version` to ensure equality across environments

---

src/context/init.js
src/services/smart-action-hook.js
src/utils/widgets.js
test/services/smart-action-hook.test.js
test/utils/widgets.test.js

fix(smart-actions): transform legacy widgets in hooks

---

src/routes/actions.js
test/routes/actions.test.js

fix: record not found in hooks (recordsId replaced with recordIds)

---

src/services/schema-file-updater.js

fix(smart-action): do not mutate hooks on schema generation

---

src/routes/actions.js

fix(smart-actions): error message details missing for hooks

---

src/routes/actions.js
test/routes/actions.test.js

fix(smart-actions): use changedField instead of comparing values to trigger the correct change hook

---

src/services/permissions-checker.js
src/services/permissions-getter.js
test/services/permissions-getter.unit.test.js
test/services/permissions.test.js

feat(role-permissions): request rendering only when needed

---

src/routes/actions.js

refactor(smart action): add a deprecation warning message when values function is declared on a smart action

---

src/services/smart-fields-values-injector.js

fix: fix related data list display

---

src/services/smart-fields-values-injector.js
test/services/smart-fields-values-injector.test.js

fix: display correct reference field when it is a smartfield

---

src/services/logger.js
src/services/oidc-client-manager.js
test/services/oidc-client-manager.test.js

refactor: add better logging on registration errors

---

CHANGELOG.md

docs(force-release): reorder the changelog

---

src/index.js
test/routes/authentication.test.js

fix(authentication): error when authenticating with an invalid token in cookies

---

src/services/smart-action-hook.js
test/services/smart-action-hook.test.js

fix(smart-action-hook): value injected to an enum field of type `[Enum]` is now correctly handled

---

commitlint.config.js

ci: switch lint length check to warning

---

src/context/init.js
src/middlewares/permissions.js
src/services/permissions-checker.js
src/services/permissions-getter.js
test/services/permissions-getter.unit.test.js
test/services/permissions.test.js

refactor(permissions): move permissions services into the dependency injection

---

.github/workflows/build.yml
commitlint.config.js

ci: remove limitation on commit messages line length on the body and footer

---

src/index.js

feat: expose SchemaSerializer

---

src/middlewares/permissions.js
src/services/permissions-checker.js
src/services/permissions-getter.js
test/middlewares/permissions.unit.test.js
test/services/permissions-checker.unit.test.js
test/services/permissions-getter.unit.test.js

feat(permissions): handle mutliple permissions cache

---

CHANGELOG.md
src/index.js

feat: expose schema serializer

---

README.md

docs(readme): fix the CI status badge

---

.github/workflows/build.yml
README.md

refactor(ci): simplify CI configuration

---

.github/workflows/build.yml
CHANGELOG.md
README.md
src/serializers/schema.js

chore: merge master

---

CHANGELOG.md

docs: fix a typo in the changelog

---

src/services/authorization-finder.js
src/utils/errors/authentication/authorization-error.js
test/services/authorization-finder.test.js

fix(authentication): return better errors when a user is not authorized to access a rendering

---

src/routes/authentication.js
test/routes/authentication.test.js

fix(authentication): safari cannot login on remote lianas because of third party cookies

---

src/context/init.js
src/routes/authentication.js
src/utils/join-url.js
test/utils/join-url.test.js

fix(authentication): unable to login when the agents respond to an url starting with a prefix

---

src/services/token.js
test/routes/authentication.test.js
test/services/token.test.js

fix(security): decrease the time before expiration of forest session token

---

src/middlewares/permissions.js
src/routes/stats.js
src/services/permissions-checker.js
src/services/permissions-getter.js
test/services/permissions-checker.unit.test.js
test/services/permissions.test.js

feat(security): authorised only allowed stats queries using permissions

---

src/index.js
src/routes/actions.js
src/services/smart-action-hook.js
test/routes/actions.test.js

feat(smart-action): support hooks for smart-collection

---

src/services/base-operator-date-parser.js

fix(date-filter): filtering only on hours now returns the expected records

---

src/utils/project-directory.js

refactor: reduce some code complexity

---

src/utils/project-directory.js
test/utils/project-directory.test.js

This contribution is a copy of this one here: https://github.com/ForestAdmin/forest-express/pull/693
This one is rebased, and does not include refactors mixed with the feature.
co-authored with @ArnaudRinquin

feat: support yarn 2 plug n play install mode

---

src/index.js
src/services/config-store.js

refactor: rename a variable and a function

---

src/services/exposed/abstract-records-service.js
src/services/exposed/record-creator.js
src/services/exposed/record-getter.js
src/services/exposed/record-remover.js
src/services/exposed/record-serializer.js
src/services/exposed/record-updater.js
src/services/exposed/records-counter.js
src/services/exposed/records-exporter.js
src/services/exposed/records-getter.js
src/services/exposed/records-remover.js
test/services/exposed/records-getter.test.js

feat: provide user and params to exposed services constructors

---

src/middlewares/permissions.js
test/middlewares/permissions.unit.test.js

fix: charts using groupby on relationship should not throws 403 forbidden

---

src/services/smart-action-hook.js

fix(smart-actions-change-hook): record is no longer altered and is sent correctly

---

src/services/scope-manager.js
test/services/scope-manager.test.js

feat: extend scope manager to allow patching pre-existing filters

---

src/index.js
src/routes/scopes.js
src/services/scope-manager.js
test/routes/scopes.test.js

feat: expose scope cache invalidation route

---

.gitignore

chore: add Jetbrains configuration files to gitignore

---

src/index.js
test/services/schema-file-updater.test.js

feat(schema): add embedded key stack into meta of the forestadmin schema

---

src/routes/actions.js
test/routes/actions.test.js

fix: update record getter usage in action route to use global scope

---

package.json
src/middlewares/ip-whitelist.js
src/utils/get-ip-from-request.js
test/utils/get-ip-from-request.test.js
yarn.lock

fix: correctly get the IP address from the request headers

---

.gitignore
CHANGELOG.md
package.json
src/index.js
src/middlewares/ip-whitelist.js
src/utils/get-ip-from-request.js
test/services/schema-file-updater.test.js
test/utils/get-ip-from-request.test.js
yarn.lock

chore: merge master into beta

---

src/context/init.js
src/routes/actions.js
src/services/smart-action-field-validator.js
src/services/smart-action-hook.js
test/routes/actions.test.js
test/services/smart-action-field-validator.test.js
test/services/smart-action-hook.test.js

BREAKING CHANGE: fields parameters on hook function is no longer a map of field, it is now an array.

feat(smart-action): add changedField argument on hook function

---

src/services/token.js
test/services/token.test.js

feat: include role in the user data inside the request

---

package.json
src/utils/get-ip-from-request.js
test/utils/get-ip-from-request.test.js
yarn.lock

fix: prevent IP check from failing for the proxies including the port in the headers

---

src/middlewares/permissions.js
src/services/models-manager.js
test/middlewares/permissions.unit.test.js

This breaking change was not required (I noticed while trying to document)

fix: remove breaking change smart action middleware

---

.github/workflows/build.yml

chore: fix the version of semantic release used for releasing the package

---

src/context/init.js
src/services/oidc-client-manager.js
test/routes/authentication.test.js
test/services/oidc-client-manager.test.js

 error during authentication when the environment secret passed as a liana option and not an environment variable

---

src/context/init.js
src/services/oidc-client-manager.js
test/routes/authentication.test.js
test/services/oidc-client-manager.test.js

Reverts ForestAdmin/forest-express#750

chore: revert "error during authentication when the environment secret passed as a liana option and not an environment variable"

---

src/context/init.js
src/services/oidc-client-manager.js
test/routes/authentication.test.js
test/services/oidc-client-manager.test.js

fix(authentication): error during authentication when the environment is secret passed as a liana option and not an environment variable

---

src/services/smart-fields-values-injector.js

fix(related-data): reaching an embedded has-many relationship by URL does not display any records on mongoose

---

src/middlewares/permissions.js
test/middlewares/permissions.unit.test.js

 fix: handle composite primary key case when checking permissions for smart actions

---

src/context/init.js
src/deserializers/smart-action-hook.js
src/routes/actions.js
test/routes/actions.test.js

chore: edit smart action hook routes to use JSONAPI request format

---

src/routes/resources.js
test/routes/resources.test.js

user and timezone was not passed to remove many => it crashed
This is either
- a regression from scopes implementation
- failed merge?

fix(actions): provide user and timezone to remove many action

---

src/routes/resources.js
test/routes/resources.test.js

fix(update): fix update regression when using scopes

---

src/index.js
test/index.test.js

feat(nested-fields-mongoose): unflatten data in the request

---

src/index.js
test/index.test.js

feat(mongoose-nested-fields): generate flattened fields in schema

---

src/index.js
test/index.test.js

chore: regroup Flattener functions

---

src/index.js

chore: rename flatten to fieldsToFlatten

---

src/serializers/resource.js
test/fixtures/cars-schema.js
test/serializers/resource.test.js

fix: use Flattener functions in resource serializer

---

src/services/exposed/record-serializer.js
src/services/exposed/records-getter.js

fix(exposed): reduce number of mandatory parameters in records-getter and record-serializer

---

src/routes/stats.js
test/routes/stats.test.js

fix(charts): objective charts now returns correct values

---

src/services/token.js
test/services/token.test.js

feat: include tags in the user data inside the request

---

src/index.js
src/services/base-filters-parser.js
src/utils/schema.js
test/services/base-filters-parser.test.js
test/utils/schema.test.js

fix(smart field): fix filter on smart references

---

src/utils/schema.js
test/utils/schema.test.js

fix(filter): fix filter on field not existing to not throw an invalid error

---

src/services/exposed/records-getter.js

fix(segment): regression after fixing performance issue, segments were ignored by ids loader

---

package.json
yarn.lock

fix(security): patch semantic-release dependencies vulnerabilities

---

yarn.lock

fix(security): patch dependencies of dependencies vulnerabilities

---

src/services/csv-exporter.js
test/services/csv-exporter.test.js

fix(export): flattened fields are now correctly exported

---

package.json
yarn.lock

chore: deprecate old versions without error when releasing a version

---

src/middlewares/count.js
test/middlewares/deactivate-count.unit.test.js

fix: prevent count middleware to crash

---

package.json
yarn.lock

You can find all the vulnerabilities [here](https://forest.slite.com/app/docs/wcubOYnJ6UBiNV)

fix(vulnerabilites): remove async dependency vulnerability

---

src/services/smart-action-field-validator.js
test/services/smart-action-field-validator.test.js

fix: log an error when smart action enums field contain null or undefined option

---

src/index.js

fix(cors): add access controll allow private network handling

---

src/index.js

[Clickup task](https://app.clickup.com/t/283apge)
[Story](https://forest.slite.com/app/docs/h1B5pyAgdPnBZ3#6f221fdf)

feat(flattener): native flattened fields are now entirely introspected

---

package.json
yarn.lock

fix(security): update moment to 2.29.4 to fix a vulnerability

---

src/serializers/resource.js
test/serializers/resource.test.js

fix(flattener): smart action availability now works properly on segments

---

jest.config.js
src/middlewares/permissions.js
src/services/permissions-checker.js
src/services/token.js
test/middlewares/permissions.unit.test.js
test/services/permissions-checker.unit.test.js
test/services/permissions.test.js
test/services/scope-manager.test.js

fix(charts): user with permissions level that allows charts creation or edition should always be allow to perform charts requests

---

.github/workflows/build.yml
.releaserc.js

chore: allow to release fixes on v8

---

.releaserc.js

chore: correctly release beta versions

---

package.json
src/routes/stats.js
src/services/authorization.ts
src/services/base-filters-parser.js
test/services/authorisation.unit.test.ts
test/services/authorization.unit.test.ts
yarn.lock

fix(chart): improve security on chart and rename keys

---

package.json
src/context/build-services.js
src/routes/stats.js
test/routes/stats.test.js
yarn.lock

feat(chart): add support for context variables inside SQL query

---

package.json
yarn.lock

chore(force-release): update forestadmin-client to fix qs vulnerability

---

src/services/exposed/error-handler.js
test/services/exposed/error-handler.test.js

refactor: support custom errors with data

---

src/services/authorization/action-authorization.ts
src/services/authorization/errors/approval-not-allowed-error.ts
src/services/authorization/errors/custom-action-requires-approval-error.ts
src/services/authorization/errors/custom-action-trigger-forbidden-error.ts
src/services/authorization/errors/invalid-action-condition-error.ts
src/services/exposed/error-handler.js
src/utils/errors/authentication/authorization-error.js
src/utils/errors/authentication/inconsistent-secret-rendering-error.js
src/utils/errors/authentication/secret-not-found-error.js
src/utils/errors/authentication/two-factor-authentication-required-error.js
test/services/authorization/action-authorization.unit.test.ts

fix(errors): error name should always be the right one

---

package.json
yarn.lock

fix(requires-approval): development environment should trigger without requiring an approval

---

yarn.lock

fix(security): patch got dependency vulnerability

---

src/index.js

fix: fix express jwt configuration after dependencies upgrade

---

src/middlewares/permissions.js
src/services/authorization/action-authorization.ts
src/services/authorization/errors/unsupported-conditional-error.ts
test/middlewares/permissions.unit.test.js
test/services/authorization/action-authorization.unit.test.ts

>Issue: CU-#860q0f82b
#860q0f82b

fix(middlewares): users should be able to execute a smart action on a smart collection

---

src/context/build-services.js
src/context/build-values.js
src/index.js

fix(init-options): mutate forest admin client options using liana options

---

package.json
src/context/build-services.js
yarn.lock

feat(events-subscription): allow to instantly refresh permissions when they change

---

package.json
src/context/build-services.js
src/context/service-builder.js
src/index.js
test/context/index.test.js
test/helpers/create-server.js
test/index.test.js
yarn.lock

fix: allow to instantly refresh permissions when they change

---

src/context/build-services.js
src/index.js
test/index.test.js

fix(event-source): gracefully close the app on exit by deactivating server events subscription

---

src/index.js
test/index.test.js

fix(event-source): gracefully close the app on exit by removing server events subscription

---

src/index.js

fix: add warnings in the console when the schema is not updated because of NODE_ENV value

---

yarn.lock

fix(security): patch debug dependency vulnerabilities

---

package.json
yarn.lock

fix: user receives 403 on newly created segment query

---

yarn.lock

fix(security): patch express dependency vulnerabilities

---

src/services/authorization/authorization.ts

fix: typo in error message when a user is not authorized to perform an action

---

package.json
src/services/csv-exporter.js
yarn.lock

fix: csv stringify import breaks build

---

src/serializers/schema.js

feat: action forms can define a submit button label and a description

---

src/services/apimap-sender.js
src/services/forest-server-requester.js
src/services/ip-whitelist.js
src/utils/timeout-error.js
test/services/apimap-sender.test.js
test/utils/timeout-error.test.js

feat: better logs during timeout

---

package.json
yarn.lock

feat: bump forestadmin-client version from 1.26.2 to 1.35.0

---

package.json
yarn.lock

fix: upgrade @forestadmin/client to fix user perm cache issue

---

.github/workflows/build.yml
src/services/forest-server-requester.js

fix: increase default forest timeout to 30sec
