ForestAdmin/forest-express

- index.js
I'm currently trying to host my Forest code on Amazon Lambda + API Gateway, using Claudia.js (I'm curious to know if anyone has already tried it).
I have not yet succeeded, but I'll send PRs as I fix the errors I encounter.
The first error that I encountered was with Bluebird. For some reason, when Claudia tries to pack my app and send it to Lambda, `P.promisifyAll(require('fs'));` complains about trying to promisify an async method.
Promisifying only readdir (instead of all of fs) solved it, while also making code initialization more efficient :-)
> Only promisify readdir

- CHANGELOG.md
- serializers/resource.js
Prevent to have JSON API objects having types with camel case (ex: `setupGuide`) that could generate an error on the client. And use kebab case instead (ex: `setup-guide`).
> [*] Records Serialization - Fix the object types case (kebab case) to prevent potential JSON api adapter errors on client side

- CHANGELOG.md
- integrations/intercom/index.js
- integrations/intercom/services/intercom-attributes-getter.js
- integrations/intercom/services/intercom-conversations-getter.js
- integrations/intercom/setup.js
Fixes: https://github.com/ForestAdmin/forest-express/issues/56
Old integration attributes:
```javascript
app.use(Liana.init({
// ...
integrations: {
intercom: {
appId: 'YOUR_INTERCOM_APP_ID',
apiKey: 'YOUR_INTERCOM_API_KEY',
intercom: require('intercom-client'),
mapping: 'user'
}
}
}));
```
New integration attributes:
```javascript
app.use(Liana.init({
// ...
integrations: {
intercom: {
accessToken: 'YOUR_INTERCOM_ACCESS_TOKEN',
intercom: require('intercom-client'),
mapping: 'user'
}
}
}));
```
> [-] Intercom Integration - Prefer Intercom accessToken configuration to old fashioned appId/apiKey

- CHANGELOG.md
- utils/code-syntax-inspector.js
Fix: https://github.com/ForestAdmin/forest-express-mongoose/issues/70
> [*] Initialisation - Prevent bad "import" syntax error detections on initialisation

- CHANGELOG.md
- index.js
Hi,
We realized that forest has a hardcoded filter and that it loads only .js files. With this pull request it can also load .ts (TypeScript) files, and therefore can run in a TypeScript environment. 
The change is very simple and should not have any impact on anything else
Thanks
> Support loading typescript modules

- index.js
ts support is amazing. But importing *.ts will lead to exceptions on .d.ts declaration files.
is included in the changelog under the current entry for ts support.
> [*] TypeScript Support - Fix TypeScript load by not importing declarations

- CHANGELOG.md
- src/index.js
In this PR I've fixed a bug where reinitializing the liana would remove collection routes.
With the existing logic, the first initialization would act normally. The second initialization would set `app` to a bare/empty Express app. This bare app would not match any routes and would return a 404 error for all requests.
We fix this by using memoization to return the already-initialized app if possible.
This bug appears when using Forest admin with AWS Lambda/Serverless/Serverless-offline. Lambda sometimes reuses containers where the code has already been initialized. But we can't make assumptions so we must reinitialize. We were seeing issues where multiple requests would be sent to the Lambda. The first request would succeed, and any following requests would fail because of the …
> Bugfix: reinitializing liana breaks Forest app

- CHANGELOG.md
- src/integrations/intercom/services/conversations-getter.js
The intercom API is returning `null` for the conversation assignee for an automated message. This checks whether the assignee is null before checking the type. Sample Intercom API response:
```
{ type: 'conversation',
id: '24156263610',
created_at: 1571353688,
updated_at: 1571353997,
waiting_since: null,
snoozed_until: null,
conversation_message:
{ type: 'conversation',
id: '432215031',
delivered_as: 'automated',
subject: '',
body:
'REDACTED',
author:
{ type: 'admin',
id: '3223231',
name: 'REDACTED',
email: 'REDACTED },
attachments: [],
url: null },
user: { type: 'user', id: '5cdce86e66f2345688008237' },
customers: [ { type: 'user', id: '5cdce86e66f2345688008237' } ],
assignee: null,
open: true,
state: 'open',
read: true,
tags: { type: 'tag.list', tags: [] },
customer_first_reply: null } …
```
> [*] Intercom Integration - Better handling of automated messages

- CHANGELOG.md
- src/index.js
Error thrown on initialisation `ReferenceError: beforeAll is not defined`. `beforeAll` is a Jest function in a file with a path of `db/models/__tests__/*.spec.js`. The stacktrace shows it being required in `requireAllModels`.
Forest does not require test files and no error is thrown on initialisation related to Jest functions
- Follow the convention of keeping test files with your source files; specifically have one in models directory
- Have that test file call a Jest function such as `beforeAll`
- Observe error thrown when test file is required by Forest during initialisation when models are required
> Fix - filter out common test filename patterns when requiring models

- CHANGELOG.md
- src/index.js
- src/routes/healthcheck.js
- test/routes/healthcheck.test.js
This route must: 
respond on /forest/healthcheck
be always reachable (even from different domains)
is used by Liana connection to test if server is on.
It answers 200.
> [+] Sessions - Distinguish "CORS configuration issue" and "Server down" scenarios in case of liana login error.

- CHANGELOG.md
- src/services/schema-file-updater.js
- src/utils/json.js
- test/services/schema-file-updater.test.js
- test/utils/json.test.js
Fix \r related issues & add tests
I'm not convinced by the last test of the `json.test.js` because of all the needed whitespaces, which generate ugly string. I did not found a better way to handle those (Since formatting is also a part of the `prettyPrint` function).
I've also tested `schema-file-updater.js` by generating a new lumber project with some regexp validation, which seems to produce a valid `.forestadmin-schema.json`
> [*] Schema -  Schemas having fields with escaped characters are now properly saved as valid JSON

- src/deserializers/query.js
- src/routes/associations.js
- src/routes/resources.js
- src/services/exposed/records-getter.js
- src/services/ids-from-request-retriever.js
- test/services/exposed/records-getter.test.js
BREAKING CHANGE: smart actions must now use this method (documentation has to be updated)
`RecordsGetter(myModel).getIdsFromRequest(myRequest)` take a `req` object and can handle either a `req.body.data.attributes.ids` (current behavior posted by frontend when selecting some items) or `req.body.data.attributes.query` (just like the current system that request backend with a filter to display in tables views). `excludedIds` can be happened to the actual `req.body.data.attributes` to filter out some IDs (select all but some).
_don't forget to update documentation after release_
```javascript
// BEFORE:
router.post('/actions/mark-as-live', async (req, res) => {
let companiesIds = req.body.data.attributes.ids;
// ...
});
// AFTER:
router.post('/actions/mark-as-live', async (req, res) => {
let …
```
> feat(smart actions): add a method to RecordsGetter to get all models IDs given a query or an ID list

- src/services/ids-from-request-retriever.js
I choose to be consistant with export csv implementation:
- batch size is 1000 (still arbitrary but now "coherent")
- order result by ID. Caveats: it only takes the first ID when there are [multiple primary keys](https://forestadmin.slack.com/archives/GAZF5Q5RV/p1582809048023700) because it's not implemented in `setOrder` methods
> fix: use export csv batch configuration in IdsFromRequestRetriever

- .travis.yml
The warnings we had in Travis:
About `skip_cleanup`:
(https://blog.travis-ci.com/2019-08-27-deployment-tooling-dpl-v2-preview-release)
> ci: remove configuration warnings

- .travis.yml
Before: more that 2 minutes (if we also lint commit messages, not included in the screenshot below)
After: 45 seconds
> ci: speed up linting and testing

- src/services/exposed/record-serializer.js
The issue is that the `RecordSerializer` usage is different between `forest-express-sequelize` and `forest-express-mongoose`. Especially when used on SmartCollection.
```js
// On forest-express-sequelize
const serializer = new RecordSerializer({ name: 'my-smart-collection' });
// On forest-express-mongoose
const serializer = new RecordSerializer({ modelName: 'my-smart-collection' });
```
```js
// Whatever the liana
const serializer = new RecordSerializer({ name: 'my-smart-collection' });
```
> fix(record serializer): harmonize the usage of the RecordSerializer

- src/index.js
- src/services/login-handler.js
- src/utils/token-checker.js
- test/utils/token-checker.test.js
[ClickUp](https://app.clickup.com/t/6mv6jr)
🚧 To test it, add FOREST_2FA_SECRET_SALT as an environment variable, and set it to a wrong value (or either a null value). If you start you server, you should see a log message stating that your token is not valid. Going further, if you try to login by using the 2FA flow, you should see an error on your web app.
A value is considered as wrong if the string is not 20 characters long, and if it is not composed of hexadecimal characters only. 
If you set a correct token, you should not see any error message (either on your server, and the web app) 🚧
> fix(2FA): throw a clear error when the 2FA salt is invalid

- src/integrations/intercom/services/attributes-getter.js
This returns `null` if no contact is found in Intercom response body.
Returning `null` complies with current behaviour for other requests. Returning a 404 error is not properly handled by the admin interface for the time beeing.
Linked to: CU-6mqmhe
> fix(integration): prevent 500 errors if Intercom record is not found

- src/routes/authentication.js
- test/routes/authentication.test.js
…d of returning the url
Linked to CU-96whq6
> feat(authentication): redirect after first authentication step instead of returning the url

- src/routes/associations.js
Linked to CU-a2z7p8
I don't see how to test this modification either with unit tests or integration tests with the current architecture of `forest-express`.
> fix: don't compute smart fields when not requested on associated records

- src/serializers/schema.js
Adding a comment to help us understand the purpose of "order" in `SchemaSerializer`
See:
> https://github.com/ForestAdmin/forest-express/blob/master/src/serializers/schema.js#L9
WARNING: Attributes declaration order is important for .forestadmin-schema.json format.
On sait pourquoi et quel ordre il faut donner ? (pour pas que je fasse de bêtises)
> Arnaud:f-forest:  8 minutes ago
par ordre d’importance des propriétés pour rendre la lecture des objets facile dans le JSON
> Arnaud:f-forest:  6 minutes ago
(en tout cas les clés qui définissent des caractéristiques proches sont côte à côte)
> chore: add comment to undestand why the order is important in SchemaSerializer

- src/context/init.js
I need `string` utility as inject to refactor `src/routes/actions.js` to develop this feature: https://app.clickup.com/t/a6yc11. PR waiting for this: https://github.com/ForestAdmin/forest-express/pull/538
> refactor: add string utils in init

- src/context/init.js
- src/generators/schemas.js
- test/generators/schemas.test.js
I need `schemas` generator as inject to refactor `src/routes/actions.js` to develop this feature: https://app.clickup.com/t/a6yc11. PR waiting for this: https://github.com/ForestAdmin/forest-express/pull/538
> refactor: add schemas generator in init

- .travis.yml
Build fails due to log size: https://travis-ci.com/github/ForestAdmin/forest-express/jobs/443393577
Since we are not using [dpl v2](https://docs.travis-ci.com/user/deployment-v2) we have to get `skip_cleanup: true` back even if it triggers a warning (source: https://github.com/ForestAdmin/forest-express/pull/381). Sources: 
- Documentation about `skip_cleanup: true` in dpl v2: https://docs.travis-ci.com/user/deployment-v2#cleaning-up-the-git-working-directory
- Issue I opened in Travis community forum: https://travis-ci.community/t/large-number-of-node-modules-js-already-exists-no-checkout-log-messages/10627/3?u=rap2h
- Semantic release: https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/travis.md#nodejs-projects-configuration
> ci: add skip_cleanup back to avoid build fail

- src/index.js
- src/routes/authentication.js
- src/routes/sessions.js
- src/services/token.js
- test/routes/authentication.test.js
- test/services/token.test.js
> feat: logout beta

- src/middlewares/permissions.js
- src/services/permissions-checker.js
- test/services/permissions.test.js
> refactor: rewrite the permissions checker as a class

- src/context/init.js
- src/routes/actions.js
- src/services/smart-action-hook.js
- test/routes/actions.test.js
- test/services/smart-action-hook.test.js
> feat(smart actions): endpoint that handle forms' load hooks

- src/utils/widgets.js
- test/utils/widgets.test.js
> fix(smart-action): widgetEdit should not be erased when change hook is triggered

- src/services/smart-action-hook.js
- test/services/smart-action-hook.test.js
> fix(smart-actions): reset value when not present in enums in hook response

- jest.config.js
- package.json
- src/middlewares/permissions.js
- src/services/permissions-checker.js
- src/services/permissions-getter.js
- test/services/permissions-getter.unit.test.js
- test/services/permissions.test.js
- yarn.lock
> feat(role-permissions): support the new role ACL format

- src/services/oidc-client-manager.js
- test/routes/authentication.test.js
- test/services/oidc-client-manager.test.js
> fix(auth): oidc authentication when running multiple instances of the agent

- src/routes/authentication.js
- test/routes/authentication.test.js
There was an [issue](https://app.clickup.com/t/c0xx0v) with Safari which does not allow to set cookie between cross domain by default so there is a little change with the authentication flow.
> fix: allow to authenticate with Safari

- src/routes/authentication.js
- src/routes/sessions.js
- test/routes/authentication.test.js
- test/routes/sessions.test.js
> fix: user being disconnected after 33min instead of 14 days

- src/index.js
- test/index.test.js
CC complains about diff-coverage being not sufficient, but I don't think I'll be able to test the `map: xxx` code without reworking the `index.js` file. Using the real `require-all` module instead of a mock implies that I need to have a whole directory with files, which should contains syntax error in order to test the behavior I added.
If you find have any good idea on how I can test this function without loads of fixtures...
> fix(forestadmin-schema): regenerate forestadmin schema only when files are valid

- src/services/authorization-finder.js
- src/services/exposed/error-handler.js
- src/utils/error-messages.js
- src/utils/errors/authentication/inconsistent-secret-rendering-error.js
- src/utils/errors/authentication/secret-not-found-error.js
- src/utils/errors/authentication/two-factor-authentication-required-error.js
- test/services/authorization-finder.test.js
- test/services/exposed/error-handler.test.js
This modification is needed to identify why the authorization failed, and display the correct error message in the frontend.
In this case, instead of a 500 with an error message, we get a 403 and the error's name correctly encoded in the response, just as the server sends errors.
Linked to CU-ccukn4
> feat(authentication): return a specific error during authorization if received an error about 2FA

- src/serializers/schema.js
- [forest-express-sequelize](https://github.com/ForestAdmin/forest-express-sequelize/pull/598)
- [forest-admin](https://github.com/ForestAdmin/forestadmin/pull/2898)
- [forest-admin-server](https://github.com/ForestAdmin/forestadmin-server/pull/2009)
Please follow in the right order theses steps, as there is still an issue with the forestadmin-server update
1. Switch to the `fix-primary-foreign-key-to-primary-key` on every projects
2. Launch forestadmin-server and forestadmin
3. In the forest-express project, run `yarn build:watch`
4. In the forest-express-sequelize, run `yarn link forest-express`, then `yarn build:watch`
5. Create a postgresql database with this dump:
```
create table if not exists customer
(
id serial not null
constraint customer_pk
primary key,
name varchar not null
); …
```
> fix: fix record creation with unconventional pk field acting as a fk

- src/index.js
- src/services/path.js
- test/services/path.unit.test.js
Linked to: CU-fuz99h.
Before
* with parentApp: /*
* without parentApp: /forest/*
After
* with parentApp: /*
* without parentApp: [/forest, /forest/*]
> fix: include `/forest` route in CORS and authentication config

- src/context/init.js
- src/index.js
- src/services/scope-service.js
Requires this backend [PR](https://github.com/ForestAdmin/forestadmin-server/pull/2427) to expose the `liana/scopes` route
No cache and security for now, this is a POC
Import the `scopeService` in `forest-express-sequelize`:
```
import { scopeService } from 'forest-express';
scopeService.getScopes(renderingId);
```
> feat(scopes): add scope retrieval service

- src/integrations/intercom/serializers/intercom-attributes.js
- test/integrations/intercom/serializers/intercom-attributes.test.js
> fix(intercom): fix date conversion from unix timestamp to js date of intercom attributes

- src/context/init.js
- src/services/permissions-formatter.js
- src/services/permissions-getter.js
- test/services/permissions-getter.unit.test.js
- test/services/permissions.test.js
> fix: stats permissions should be retrieved only one time per team

- src/middlewares/permissions.js
- src/services/models-manager.js
> fix(smart-action): smart action after trying to mitigate breaking change

- src/services/permissions-checker.js
- src/services/permissions-formatter.js
- src/services/permissions-getter.js
- test/services/permissions.test.js
> feat(security): secure segments queries

- src/serializers/resource.js
> fix(has many): fix link of has many

- package.json
- src/context/build-services.js
- src/routes/stats.js
- test/routes/stats.test.js
- yarn.lock
> feat(chart): add support for context variables used by Workspaces

- src/services/exposed/record-serializer.js
- test/services/exposed/record-serializer.test.js
> fix(serialiser): serialiser does not compute hidden smart fields anymore

- package.json
- yarn.lock
> fix: typo in error messages

- package.json
- src/routes/associations.js
- src/routes/resources.js
- src/services/csv-exporter.js
- src/services/smart-fields-values-injector.js
- yarn.lock
> perf(export): improve memory usage when exporting data

- src/context/build-services.js
- src/routes/actions.js
- src/services/smart-action-form-layout-service.js
- src/services/smart-action-hook-service.js
- test/routes/actions.test.js
- test/services/smart-action-form-layout-service.test.js
- test/services/smart-action-hook-service.test.js
> feat: support layout elements in smart action form hooks
